Added specification of "." library, into which "src/" is compiled, so that executing a runtime workbench that takes Polyglot from the workspace works correctly (no NoClassDefFoundError's).